export enum PAYMENT_TERMS {
  PAYMENT_TERMS_AS_DATE = "PAYMENT_TERMS_AS_DATE",
  PAYMENT_TERMS_IN_DAYS = "PAYMENT_TERMS_IN_DAYS",
  CASH_DISCOUNT_TARGET_AS_A_DATE = "CASH_DISCOUNT_TARGET_AS_A_DATE",
  CASH_DISCOUNT_TARGET_IN_DAYS = "CASH_DISCOUNT_TARGET_IN_DAYS",
  DISCOUNT_AND_PERCENTAGE = "DISCOUNT_AND_PERCENTAGE",
  DISCOUNT_AMOUNT = "DISCOUNT_AMOUNT",
  TOTAL_AMOUNT_MINUS_DISCOUNT = "TOTAL_AMOUNT_MINUS_DISCOUNT",
}
